apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf-deployment
  namespace: MY_NAMESPACE
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"AMF_ADDR\"]"
        k8s.v1.cni.cncf.io/networks: sriov-net1
    spec:
      hostname: amf
      subdomain: localdomain
      hostAliases:
      - ip: "AMF_ADDR"
        hostnames:
        - "amf.localdomain"
      - ip: "HSS_ADDR"
        hostnames:
        - "hss.localdomain"
      - ip: "SMF_ADDR"
        hostnames:
        - "smf.localdomain"
      - ip: "PCRF_ADDR"
        hostnames:
        - "pcrf.localdomain"
      - ip: "UPF_ADDR"
        hostnames:
        - "upf.localdomain"
      containers:
      - name: amf-container
        image: "sufuf3/nextepc-build:latest"
        command: ["/bin/bash"]
        args: ["-c", "ip addr add S1AP_ADDR/24 dev net1 && /usr/src/free5gc/free5gc-amfd"]
        ports:
          - containerPort: 5868
            name: api1
          - containerPort: 3868
            name: api2
        stdin: true
        tty: true
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_URI
            value: mongodb://mongo-external.MY_NAMESPACE.svc.cluster.local/nextepc
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/free5gc/install/etc/free5gc/free5gc.conf
          subPath: free5gc.conf
        - name: freediameter-volume
          mountPath: /usr/src/free5gc/install/etc/free5gc/freeDiameter/amf.conf
          subPath: amf.conf
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        resources:
          requests:
            intel.com/sriov_net: '1'
          limits:
            intel.com/sriov_net: '1'
      #hostNetwork: true
      securityContext:
        sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"
      volumes:
        - name: config-volume
          configMap:
            name: free5gc-config
            items:
            - key: config.file
              path: free5gc.conf
        - name: freediameter-volume
          configMap:
            name: freediameter-amf-config
            items:
            - key: config.file
              path: amf.conf
