apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcrf-nextepc-deployment
  namespace: MY_NAMESPACE
  labels:
    app: nextepc-pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextepc-pcrf
  template:
    metadata:
      labels:
        app: nextepc-pcrf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"PCRF_ADDR\"]"
    spec:
      hostname: pcrf
      subdomain: localdomain
      hostAliases:
      - ip: "AMF_ADDR"
        hostnames:
        - "amf.localdomain"
      - ip: "HSS_ADDR"
        hostnames:
        - "hss.localdomain"
      - ip: "SMF_ADDR"
        hostnames:
        - "smf.localdomain"
      - ip: "PCRF_ADDR"
        hostnames:
        - "pcrf.localdomain"
      - ip: "UPF_ADDR"
        hostnames:
        - "upf.localdomain"
      containers:
      - name: nextepc-pcrf
        image: "sufuf3/nextepc-build:latest"
        command: ["/bin/bash"]
        args: ["-c", "/usr/src/free5gc/nextepc-pcrfd"]
        ports:
          - containerPort: 80
            name: api
          - containerPort: 5868
            name: api1
          - containerPort: 3868
            name: api2
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_URI
            value: mongodb://mongo-external.MY_NAMESPACE.svc.cluster.local/nextepc
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/free5gc/install/etc/free5gc/free5gc.conf
          subPath: free5gc.conf
        - name: freediameter-volume
          mountPath: /usr/src/free5gc/install/etc/free5gc/freeDiameter/pcrf.conf
          subPath: pcrf.conf
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
      securityContext:
        sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"
      volumes:
        - name: config-volume
          configMap:
            name: free5gc-config
            items:
            - key: config.file
              path: free5gc.conf
        - name: freediameter-volume
          configMap:
            name: freediameter-pcrf-config
            items:
            - key: config.file
              path: pcrf.conf
