---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: base-k8s-operatot
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-synchronizer
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-synchronizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: base-k8s-operatot
subjects:
- kind: ServiceAccount
  name: kubernetes-synchronizer
  namespace: default
